VAGRANTFILE_API_VERSION = "2"  
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # config.vm.define "tomcat" do |v|
  #   v.vm.provider "docker" do |d|
  #     d.build_dir = "./dockerfiles/tomcat"
  #     d.ports = [ "8080:8080" ]
  #     d.volumes = ["/var/docker/tomcat:/webapps"]
  #     d.vagrant_vagrantfile = "./Vagrantfile.proxy"
  #   end
  # end

  config.vm.define "postgres" do |v|
    v.vm.provider "docker" do |d|
      d.image = "postgres"
      d.volumes = ["/var/docker/postgresql:/data"]
      d.ports = ["5432:5432"]
      d.vagrant_vagrantfile = "./Vagrantfile.proxy"
    end
  end

end